# Generated by Django 2.2 on 2020-04-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_disprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test Descripttion'),
            preserve_default=False,
        ),
    ]
