# Generated by Django 2.2 on 2020-04-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200428_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
